### ISSUE TITLE
pygame.error: Unknown WAVE format

### ISSUE THREAD

**Issue by Wikinaut** [codelectron/Soundboard#1]
On Raspi 2 B I didn't get your code running.

```
pip install pygame
```

fails with 
```
Collecting pygame
  Using cached https://files.pythonhosted.org/packages/61/06/3c25051549c252cc6fde01c8aeae90b96831370884504fe428a623316def/pygame-1.9.3.tar.gz
    Complete output from command python setup.py egg_info:
    
    
    WARNING, No "Setup" File Exists, Running "config.py"
    Using UNIX configuration...
    
    
    Hunting dependencies...
    SDL     : found 1.2.15
    FONT    : not found
    IMAGE   : not found
    MIXER   : not found
    PNG     : found
    JPEG    : not found
    SCRAP   : found
    PORTMIDI: not found
    PORTTIME: not found
    FREETYPE: found 2.6.3
    Missing dependencies
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-5U0TdV/pygame/
```
and when I install the pygame from debian

```
sudo apt install python-pygame
```
and then run
```
python /home/pi/Soundboard/soundbox.py
```
I got
```
Traceback (most recent call last):
  File "/home/pi/.local/lib/python2.7/site-packages/pad4pi/rpi_gpio.py", line 111, in _onKeyPress
    handler(keyPressed)
  File "/home/pi/Soundboard/soundbox.py", line 49, in processKey
    playSound(path)
  File "/home/pi/Soundboard/soundbox.py", line 14, in playSound
    mixer.music.load(path)
pygame.error: Unknown WAVE format
```

So I don't see how you got your code running.

**Comment by Wikinaut** [comment]
It was an issue of your file 1/test.wav
